### ISSUE TITLE
Bug with default values of `null` type

### ISSUE THREAD

**Issue by Joyfolk** [tarantool/avro-schema#24]
Default values are ignored for `null` typed fields and unions. 
With other types, like `int` it's working as expected

```
tarantool>  ok, schema = avro_schema.create {
    type = "record",
    name = "test",
    fields = {
      { name = "bar", type = "null", default = msgpack.NULL },
      { name = "foo", type = {"int", "null"}, default = msgpack.NULL }
    }
}
 
 
tarantool>  avro_schema.validate(schema, { foo = { int = 42 } })
---
- false
- Field bar missing
...
 
 
tarantool> avro_schema.validate(schema, { bar = msgpack.NULL })
---
- false
- Field foo missing
...
```

**Comment by bigbes** [comment]
Hello, @Joyfolk.
I've pushed [commit](https://github.com/tarantool/avro-schema/commit/152a1f0482b29580a38a35f516912ddde334bcda) to branch [`default-null`](https://github.com/tarantool/avro-schema/tree/default-null) that should fix this problem

**Comment by Totktonada** [comment]
Valid test case must have 'null' as the first item of the union and 'int' as the second one, because of a default value must have the same type as the first item of a union. With `type = {"null", "int"}` the default-null branch (commit 152a1f0482b29580a38a35f516912ddde334bcda) works as expected in that case.
